services:
  rabbitmq:
    image: rabbitmq:3.10.2-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5

  app:
    container_name: delayed-rabbit
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
        - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672